In [1]:
#import Libs
import pandas as pd

In [2]:
#Import Database
df = pd.read_csv('https://raw.githubusercontent.com/jrafa1607/DataScience-ML-AI/main/-%20Datasets/credit_data.csv')

In [3]:
#Ajust the Columns of Dataframe
df.columns = ['id', 'salario', 'idade', 'emprestimo', 'aprovado']

In [4]:
#Show the Dataframe
df

        id       salario      idade   emprestimo  aprovado
0        1  66155.925095  59.017015  8106.532131         0
1        2  34415.153966  48.117153  6564.745018         0
2        3  57317.170063  63.108049  8020.953296         0
3        4  42709.534201  45.751972  6103.642260         0
4        5  66952.688845  18.584336  8770.099235         1
...    ...           ...        ...          ...       ...
1995  1996  59221.044874  48.518179  1926.729397         0
1996  1997  69516.127573  23.162104  3503.176156         0
1997  1998  44311.449262  28.017167  5522.786693         1
1998  1999  43756.056605  63.971796  1622.722598         0
1999  2000  69436.579552  56.152617  7378.833599         0

[2000 rows x 5 columns]

In [5]:
#Detecting Negative Values in the Dataframe ( LT = Lower Than... )
print(df.lt(0).sum())

id            0
salario       0
idade         3
emprestimo    0
aprovado      0
dtype: int64

In [6]:
#Check the Negative Values
df[df['idade'] < 0]

    id       salario      idade   emprestimo  aprovado
15  16  50501.726689 -28.218361  3977.287432         0
21  22  32197.620701 -52.423280  4244.057136         0
26  27  63287.038908 -36.496976  9595.286289         0

In [7]:
#Example 01 - Remove the Attribute from Database
df_test = df.drop(['idade'], axis = 1)
print(df_test)

        id       salario   emprestimo  aprovado
0        1  66155.925095  8106.532131         0
1        2  34415.153966  6564.745018         0
2        3  57317.170063  8020.953296         0
3        4  42709.534201  6103.642260         0
4        5  66952.688845  8770.099235         1
...    ...           ...          ...       ...
1995  1996  59221.044874  1926.729397         0
1996  1997  69516.127573  3503.176156         0
1997  1998  44311.449262  5522.786693         1
1998  1999  43756.056605  1622.722598         0
1999  2000  69436.579552  7378.833599         0

[2000 rows x 4 columns]

In [8]:
#Example 02 - Remove the Lines from Database
df_test = df.drop(df[df['idade'] < 0].index)
print(df_test)

        id       salario      idade   emprestimo  aprovado
0        1  66155.925095  59.017015  8106.532131         0
1        2  34415.153966  48.117153  6564.745018         0
2        3  57317.170063  63.108049  8020.953296         0
3        4  42709.534201  45.751972  6103.642260         0
4        5  66952.688845  18.584336  8770.099235         1
...    ...           ...        ...          ...       ...
1995  1996  59221.044874  48.518179  1926.729397         0
1996  1997  69516.127573  23.162104  3503.176156         0
1997  1998  44311.449262  28.017167  5522.786693         1
1998  1999  43756.056605  63.971796  1622.722598         0
1999  2000  69436.579552  56.152617  7378.833599         0

[1997 rows x 5 columns]

In [9]:
#Example 03 - Replace for the Mean of Positive Values

#Find the Media Value
media = df['idade'][df.idade > 0].mean()
print(media, "\n")

#Replace the Negative Values
df.loc[df.idade < 0, 'idade'] = media
print(df.lt(0).sum(), "\n")

40.92770044906149

id            0
salario       0
idade         0
emprestimo    0
aprovado      0
dtype: int64

In [10]:
#Show the Lines after Replace Values for the Mean of the Positive Values
print(df.loc[15], "\n")
print(df.loc[21], "\n")
print(df.loc[26], "\n")

id               16.000000
salario       50501.726689
idade            40.927700
emprestimo     3977.287432
aprovado          0.000000
Name: 15, dtype: float64

id               22.000000
salario       32197.620701
idade            40.927700
emprestimo     4244.057136
aprovado          0.000000
Name: 21, dtype: float64

id               27.000000
salario       63287.038908
idade            40.927700
emprestimo     9595.286289
aprovado          0.000000
Name: 26, dtype: float64